AWSTemplateFormatVersion: 2010-09-09
Resources:
  DevEC2Instance:

    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: ami-0d542ef84ec55d71c
      InstanceType: t2.micro
      KeyName: cfn-key-1
      SecurityGroups:
        -  default
        -  !Ref SSHSecurityGroup
#So now we going to create security group,it's new resource
  SSHSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: my new ssh SG
      SecurityGroupIngress:
        -  IpProtocol: tcp
           FromPort: '8080'
           ToPort: '8080'
           CidrIp: 0.0.0.0/0
#Here first we creating Elastic IP and then refering it to EC2 instance
  MyElasticIP:
    Type: 'AWS::EC2::EIP'
    Properties:
      InstanceId: !Ref DevEC2Instance